### ISSUE TITLE
Do we really need the pihole -g ?

### ISSUE THREAD

**Issue by Damien514** [jejje/pihole-rsync#2]
I was wondering if we really needed the `pihole -g` command?
As we rsync the whole DB, I think that a simple _stop / restart / reload list_ would be enough, or am I wrong?

Other than that, your script is simple and do all I need. Thanks for that :-)

**Comment by jejje** [comment]
Yes I think you are correct! I'd like to try it out and change it but I can't test it at the moment. I'm setting up my network from the ground up. Have you tried it and it worked?

Thank you for your appreciation, I'm really glad it was useful for you! :)

**Comment by Damien514** [comment]
Yes I did, and I can confirm it works very well.
All I changed in your script is removing the _pihole -g_ command and moving the stop pihole-FTL before the RSYNC loop and then pihole-FTL start and pihole reload-lists.

**Comment by Damien514** [comment]
Oh, and the crontab you create within the script indicates /etc/pi_rsynch.sh ; I edited it as it should be /etc/**pihole**/pi_rsynch.sh

:-)

**Comment by jejje** [comment]
I made the changes but I am unable to test it properly, but I did as you suggested and I think it will work just as before and is now better optimized

**Comment by jejje** [comment]
Made changes, please tell me if you find more optimizations!
